#!/usr/bin/sh

sxhkd &

# Monitor Detection
autorandr -c
setup="$(autorandr | grep '(current)' | cut -d' ' -f1)"
case $setup in
	mobile)
		bspc monitor eDP-1 -d 1 2 3 4 5 ;;
	docked)
		bspc monitor DP-1-1 -d 1 2 3 4 5
		bspc monitor DP-1-2 -d 6 7 8 9 ;;
	*)
		bspc monitor -d 1 2 3 4 5 ;;
esac

# Settings
bspc config border_width         15
bspc config border_radius        10
bspc config window_gap           8

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc config focus_follows_pointer	true

bspc config normal_border_color  "#2a2a2a"
bspc config focused_border_color "#565050"

# Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a feh state=floating
bspc rule -a GLava manage=off

#~/.config/polybar/start.sh # start polybar
orangebar | lemonbar -n bar -B \#c52a2a2a -F \#bebebe -f 'SF Mono:size=11' -g 1920x30+0+0 & # start lemonbar with script &
disown
orangebar | lemonbar -n bar -B \#c52a2a2a -F \#bebebe -f 'SF Mono:size=11' -g 1920x30+1920+0 &
disown
sh -c '~/.config/bspwm/borders.sh' & # double borders

nitrogen --restore # set background
numlockx on # set numlock on

picom-ibhagwan --config ~/.config/picom-bsp.conf & # start picom
