#!/usr/bin/sh

sxhkd &

# Monitor Detection
autorandr -c
setup="$(autorandr | grep '(current)' | cut -d' ' -f1)"
case $setup in
	mobile)
		bspc monitor eDP-1 -d 一 二 三 四 五 ;;
	docked)
		bspc monitor DP-1-1 -d 一 二 三 四 五
		bspc monitor DP-1-2 -d 六 七 八 九 十 ;;
	*)
		bspc monitor -d 一 二 三 四 五 ;;
esac

bspc monitor DP-1-1 -d 一 二 三 四 五
bspc monitor DP-1-2 -d 六 七 八 九 十

# Settings
bspc config border_width         15
bspc config window_gap           0

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc config focus_follows_pointer	true

bspc config normal_border_color  "#2a2a2a"
bspc config focused_border_color "#565050"


# Rules
bspc rule -a Gimp state=floating follow=on
bspc rule -a feh state=floating
bspc rule -a GLava manage=off
bspc rule -a Pavucontrol state=floating
bspc rule -a Zathura state=tiled

bspc rule -a URxvt:URxvtZim state=float
bspc rule -a URxvt:URxvtFloat state=float
bspc rule -a URxvt:URxvtFuzzy state=float


#~/.config/polybar/start.sh # start polybar

# Start lemonbar
if pgrep coffeebar >/dev/null 2>&1 ; then
	pkill coffeebar
	pkill lemonbar
fi

case $setup in
	docked)
		coffeebar | lemonbar -n bar -B \#c52a2a2a -F \#bebebe -f 'SF Mono:size=11' -f 'Noto Serif CJK JP:style=SemiBold:size=10' -f 'Noto Sans CJK JP:size=10' -g 1920x30+0+0 &
		coffeebar 2 | lemonbar -n bar -B \#c52a2a2a -F \#bebebe -f 'SF Mono:size=11' -f 'Noto Serif CJK JP:style=SemiBold:size=10' -f 'Noto Sans CJK JP:size=10' -g 1920x30+1920+0 &
		;;
	mobile|*)
		coffeebar | lemonbar -n bar -B \#c52a2a2a -F \#bebebe -f 'SF Mono:size=11' -f 'Noto Serif CJK JP:style=SemiBold:size=10' -f 'Noto Sans CJK JP:size=10' -g 1920x30+0+0 &
		;;
esac

# Double borders
if pgrep borders.sh >/dev/null 2>&1 ; then
	killall borders.sh
	sh -c '~/.config/bspwm/borders.sh' &
else
	sh -c '~/.config/bspwm/borders.sh' &
fi


#nitrogen --restore # set background
feh --bg-fill ~/Pictures/wallpapers/cofe/coffee.jpg
numlockx on # set numlock on

picom-ibhagwan --config ~/.config/picom-bsp.conf & # start picom
